apiVersion: v1
kind: Pod
metadata:
  name: myvolsecret
spec:
  containers:
  - name: c1
    image: centos
    command: ["/bin/bash", "-c" ,"while true; do echo hello-rajani; sleep 5; done"]
    volumeMounts:
    - name: testsecret
      mountPath: "/tmp/secret"
  volumes:
  - name: testsecret
    secret:
      secretName: mysecret


