kind: Deployment
apiVersion: apps/v1
metadata:
   name: mydeployment
spec:
   replicas: 1
   selector:
     matchLabels:
        name: deployment
   template:
     metadata:
        name: testpod6
        labels:
          name: deployment
     spec:
        containers:
        - name: c00
          image: httpd
          ports:
          - containerPort: 80

