kind: ReplicaSet
apiVersion: apps/v1
metadata:
   name: myrs
spec:
   replicas: 2
   selector:
     matchExpressions:
     - {key: myname, operator: In, values: [rajani,rajan]}
     - {key: env, operator: NotIn, values: [production]}
   template:
     metadata:
        name: testpod5
        labels:
          myname: rajani
     spec:
        containers:
        - name: c00
          image: ubuntu
          command: ["/bin/bash","-c", "while true; do echo hello-srini; sleep 5; done"]

