kind: Pod
apiVersion: v1
metadata:
   name: testpod1
spec:
   containers:
   - name: c01
     image: ubuntu
     command: ["/bin/bash", "-c" ,"while true; do echo hello-Rajani;sleep 5; done"]
     env:
     - name: myname
       value: students

