kind: Pod
apiVersion: v1
metadata:
   name: testpod
   annotations:
     description: our first testpod
spec:
   containers:
   - name: c00
     image: ubuntu
     command: ["/bin/bash", "-c" ,"while true; do echo hello-Rajani;sleep 5; done"]
   restartPolicy: Never

